services:
  nginx:
    container_name: machinestore_nginx
    image: nginx:latest
    volumes:
      -  ./:/var/www/
      -  ./_docker/nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - app
  app:
    container_name: machinestore_app
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
        - db
  db:
    container_name: machinestore_db
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: machinestore
        MYSQL_ROOT_PASSWORD: hjntogn5Hnym
        MYSQL_USER: mst
        MYSQL_PASSWORD: hjntogn5Hnym
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
          PMA_HOST: db
          MYSQL_ROOT_PASSWORD: hjntogn5Hnym
      depends_on:
          - db
      ports:
          - 3001:80
